api/urls.py
from django.urls import include, path,re_path
from api import views


urlpatterns = [
    path('register/', views.RegisterAPIView.as_view(), name = 'register'),
    path('login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/', views.AuthUserAPIView.as_view(), name = 'user'),
]

urlpatterns += [
    path('<str:category>', views.QRCategoryView.as_view(), name='qr_category'), # Fetch all user QR from a category
    # path('<str:category>/<int:pk>', views.QROneCategoryView.as_view(), name='get_one'), # Fetch one user QR from a category
    path('', views.QRAPIView.as_view(), name='all_user_qr'), # Fetch all user QR
]

# Coming soon ...
# urlpatterns = [
#     path('<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category    
#     path('<int:id>/category/create/', views), # Create a new QR in a category ... coming soon
#     path('<int:id>/category/edit/', views), # edit a QR in a category ... coming soon
#     path('<int:id>/<str:category/delete', views.), # Delete all user QR from a category
#     path('<str:category>/<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category
#     path('<int:id>/delete', views.), # Delete all user QR from all categories
# ]

qr_gen_project/urls.py
# qr_gen_project/settings.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.contrib import admin
from django.urls import path


schema_view = get_schema_view(
   openapi.Info(
      title="QR Planets API Documentation",
      default_version='v1',
      description="""The Easiest Way to generate, download &amp; share QR Codes Online with QR Planet Code Generator within few minutes.
      Get started today.
      These are the Available Endpoints, Other API Endpoints are coming soon""",
      
      contact=openapi.Contact(email="simplenick01@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[]
)


urlpatterns = [
   path('api/documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='docs'),
   path('qr-gen/api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   path('qr-gen/api/', include('api.urls'), ),
]


urlpatterns += [
    path('', include('qr_generator.urls', namespace='qr_generator'),),
    path('qr-gen/admin/', admin.site.urls),
]

urlpatterns += [
    path('qr-gen/accounts/', include('accounts.urls', namespace='accounts'),),
]

urlpatterns +=[
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT, }), ]

handler404 = "qr_generator.views.page_not_found"

qr_generator/urls.py
from django.urls import path
from qr_generator import views


app_name = 'qr_generator'

urlpatterns = [
    path('', views.index, name="home"),
]

urlpatterns += [
    path('generate-qr/', views.generate_qr, name='generate_qr'),
    path('share-qr/<str:pk>/', views.share_qr, name='share'),
    path('download-qr/<str:id>/<str:file_type>/', views.download_file, name='download'),
    path('save-qr/<str:id>/', views.save_qr, name='save_qr'),
]

urlpatterns +=[
    path('contact-us/', views.contact_us, name='contact_us'),
    path('learn-more/', views.learn_more, name="learn_more"),
    path('about-us', views.about_us, name='about_us'), 
]


urlpatterns += [
    path('dashboard/active-qr', views.dashboard, name='active_qr',),
    path('dashboard/folders/', views.folders, name='folders'),

]

qr_generator/models.py
# account/models.py
from io import BytesIO
from qrcode import *
import qrcode
from django.utils import timezone
from django.core.files import File
from django.db import models
from django.contrib.auth import get_user_model
from qr_gen_project.settings import MEDIA_URL, STATIC_ROOT, STATIC_URL, MEDIA_ROOT


from django.db import models
import qrcode
from PIL import Image, ImageDraw
from io import BytesIO
from django.core.files import File
OUR_LOGO = STATIC_ROOT + '/base/images/' + 'qr_logo.png'
import random
import datetime



# Todo: extend the base user model and override to __str__ method to return name
User = get_user_model()


def get_current_time():
    now = str(datetime.datetime.now()).split('.')
    return str(now[1])


class Category(models.Model):
    """Every Available category"""
    category_name = models.CharField(primary_key=True, max_length=250, unique=True)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        db_table = 'category'
        verbose_name_plural = 'categories'


class QRCollection(models.Model):
    """All QR collections available"""
    qr_user = models.ForeignKey(User, on_delete=models.CASCADE, )
    category = models.CharField(max_length=200, blank=True, null=True)
    time_created = models.DateTimeField(auto_now_add=True)
    
    qr_code = models.ImageField(upload_to='all_qr/')
    qr_info = models.CharField(max_length=200, blank=True, null=True)

    def save(self,*args,**kwargs):
        our_logo = Image.open(OUR_LOGO)
    
        # adjust image size
        widthpercent = (100/float(our_logo.size[0]))
        hsize = int((float(our_logo.size[1])*float(widthpercent)))
        our_logo = our_logo.resize((100, hsize), Image.ANTIALIAS)

        QRcode = qrcode.QRCode(
        version=3,
        box_size = 10,
        border=2,
        error_correction=qrcode.constants.ERROR_CORRECT_M
        )
        QRcode.add_data(self.qr_info)
        QRcode.make(fit=True)
    
        QRimg = QRcode.make_image(
            fill_color='black', back_color="white").convert('RGB')

         # set size of QR code
        pos = (
            (QRimg.size[0] - our_logo.size[0]) // 2,
            (QRimg.size[1] - our_logo.size[1]) // 2
            )

        QRimg.paste(our_logo, pos)
        buffer=BytesIO()
        QRimg.save(buffer, 'PNG')
        self.qr_code.save(f'{self.qr_user.username}{random.randint(0,9999)}.png',File(buffer),save=False)
        print(self.qr_code)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.qr_user.username}\'s {self.category} {self.id}'


    class Meta:
        db_table = 'qr_collection'
        verbose_name_plural = 'qr_collections'

class UserCollection(models.Model):
    """A simple abstraction of the Collections for a user"""
    qr_user = models.ForeignKey(User, on_delete=models.CASCADE,)
    qr_code = models.IntegerField()

    def __str__(self):
        return str(self.qr_user)

    class Meta:
        db_table = 'user_collection'
        verbose_name_plural = 'user_collections'

qr_generator/forms.py
from django import forms


class ContactUsForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder':'Full Name',
                'required':True,
                'name':'name',
                'type':'text',
                'id':'required'
                }
                ))


    email = forms.CharField(
        widget = forms.TextInput(
                attrs={
                    'placeholder':'Email',
                    'required':True,
                    'id':'required',
                    'type':'email',
                    'name':'email',
                }
            ))

    subject = forms.CharField(
        widget = forms.TextInput(
                attrs={
                    'placeholder':'Subject of Mail',
                    'required':True,
                    'id':'required',
                    'type':'text',

                }
                ))

    message = forms.CharField(
        widget = forms.Textarea(
                attrs={
                    'placeholder':'Enter your message',
                    'required':True,
                    'id':'required',
                    'name':'message',
            })
        )

qr_generator/views.py
# account/views.py
import base64
from smtplib import SMTPServerDisconnected
from wsgiref.simple_server import WSGIRequestHandler
from django.http import BadHeaderError, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.conf import settings

from django.core.mail import send_mail
from django.contrib import messages

from .forms import ContactUsForm 
from PIL import Image
from django.conf import settings
from qr_gen_project.settings import  MEDIA_ROOT
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

# --------------------imports

from django.shortcuts import render
from django.conf import settings
from qrcode import *
from .models import QRCollection, UserCollection


import mimetypes
import os
from django.http.response import HttpResponse
from django.shortcuts import render

User = get_user_model()


@login_required(login_url="/qr-gen/accounts/login")
def dashboard(request):
    template = 'qr_generator/dashboard/active_qr.html'
    context = {}

    try:
        user_ = UserCollection.objects.filter(qr_user=request.user)
        qr_code = [qr.qr_code for qr in user_]
        user_items = []

        # fetch the QR from QRcollections and append to the list
        [user_items.append(QRCollection.objects.get(id=qr)) for qr in qr_code]
        context['user_items'] = user_items
    
    except QRCollection.DoesNotExist as ex:
        messages.info(request, "No collection available")


    return render(request, template, context)


def index(request):
    context = {}
    return render(request, 'qr_generator/index.html', context)



def share_qr(request, pk):
    return render(request, 'qr_generator/share_qr.html', {'qr_image':pk})

# =========== CONVERT QR FORMATS ================

# Convert to JPEG
def convert_to_jpeg(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    jpeg_image = rgb_image.save(path.replace('.png', '.jpeg'), 'JPEG')
    return path.replace('.png', '.jpeg'), os.path.basename(path.replace('.png', '.jpeg'))

def convert_to_png(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    png_image = rgb_image.save(path.replace('.png', '.png'), 'PNG')
    return path.replace('.png', '.png'), os.path.basename(path.replace('.png', '.png'))

# Convert to JPG
def convert_to_jpg(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    jpg_image = rgb_image.save(path.replace('.png', '.jpg'), 'JPG')
    return path.replace('.png', '.jpg'), os.path.basename(path.replace('.png', '.jpg'))


# Convert to SVG
def convert_to_svg(path):
    startSvgTag = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
    "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="240px" height="240px" viewBox="0 0 240 240">"""
    endSvgTag = """</svg>"""
    pngFile = open(path, 'rb')
    base64data = base64.b64encode(pngFile.read())
    base64String = '<image xlink:href="data:image/png;base64,{0}" width="240" height="240" x="0" y="0" />'.format(base64data.decode('utf-8'))
    f = open(path.replace('.png', '.svg'), 'w')
    f.write(startSvgTag + base64String + endSvgTag)
    f.close()
    return path.replace('.png', '.svg'), os.path.basename(path.replace('.png', '.svg'))


# Convert to PDF
def convert_to_pdf(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    pdf_image = rgb_image.save(path.replace('.png', '.pdf'), 'PDF')
    return path.replace('.png', '.pdf'), os.path.basename(path.replace('.png', '.pdf'))

# =========== ENDCONVERT QR FORMATS ================


def qr_creator(request:WSGIRequestHandler, user: User, categ_: str) -> QRCollection:
    """This is the Main QR Creator Function:
        It creates the QR code and returns the created QR object
    """

    QRCollection.objects.create(
            qr_user = user,
            category = categ_.upper(),
            qr_info = 'Your {0} is: {1}.'.format(categ_.title(), request.POST[categ_])
            )

    created_qr_object = QRCollection.objects.filter(qr_user=user).order_by('-id')[0]

    return created_qr_object


@login_required(login_url="/qr-gen/accounts/login")
def generate_qr(request):
    """The Generte QR function accepts a WSGIRequest, if it's a POST request,
    it checks the name in the submitted form and uses the qr_creator function to process it """
    
    context = {}
    template = 'qr_generator/generateqr.html'
    
    if request.method == 'POST':
        
        # if text is selected        
        if 'text' in request.POST:
            context['qr_object'] = qr_creator(request.POST, request.user, 'text')
            return render(request, template, context)

        # if Url is selected
        elif 'url' in request.POST:
            context['qr_object'] = qr_creator(request, request.user, 'url')
            return render(request, template, context)

        # if github  is selected
        elif 'github' in request.POST:
            context['qr_object'] = qr_creator(request, request.user, 'github')
            return render(request, template, context)

        # if zoom  is selected
        elif 'zoom' in request.POST:
            context['qr_object'] = qr_creator(request, request.user, 'zoom')
            return render(request, template, context)

        # if App-store is selected
        elif 'app-store' in request.POST:
            context['qr_object'] = qr_creator(request, request.user, 'app-store')
            return render(request, template, context)

    return render(request, template, context)

def folders(request):
    template = 'qr_generator/dashboard/folders.html'
    context = {}

    # Get all the saved QR ID's
    user_items = [item.qr_code for item in UserCollection.objects.filter(qr_user=request.user)]

    # fetch them
    all_user_items = QRCollection.objects.filter(id__in=user_items)

    unique_categories = {str(_.category) for _ in all_user_items }
    context['folders'] = unique_categories

    return render(request, template, context)

def save_qr(request, id):
    user = request.user
    UserCollection.objects.create(qr_user=user, qr_code=id)
    messages.success(request, 'Your QR has been saved!! Go to Your Dashboard to view it')
    return  render(request, 'qr_generator/generateqr.html')

def form(request, template):
    form = ContactUsForm()
    return render(request, "qr_generator/" + template +'.html', {"form":form})

def about_us(request):
    return render(request, 'base/about_us.html', )


def contact_us(request):
    template = 'base/contact_us.html'
 
    context = {}
    if request.method == "POST":
        form =  ContactUsForm(request.POST)
        if form.is_valid():
            from_email = settings.QR_EMAIL_HOST_USER
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message'] #request.POST.get('message')
            reciever = settings.QR_EMAIL_HOST_USER

            try:
                send_mail(subject, message, from_email, [reciever,])
                messages.success(request, message="Message Successfully sent!!")
                return redirect('qr_generator:home')
            except BadHeaderError:
                messages.error(request, message="Invalid Header")
                return HttpResponse('Invalid header found.')

            except SMTPServerDisconnected:
                messages.error(request, message="Network Connection failed")
                return redirect(to='qr_generator:contact_us')

            except Exception as err:
                return HttpResponse("We haven't encountered this problem before") # TODO: will fix this when error page comes

        else:
            messages.info(request, 'One or more fields are empty!!')
            return render(request, template, context)

            
    else:
        form = ContactUsForm()

    context['form'] = form
    
    return render(request, template, context)


# Define function to download pdf file using template
def download_file(request, id='', file_type=''):


    if id != '':
        file = QRCollection.objects.get(id=id).qr_code
        obj = MEDIA_ROOT + '/' + str(file)


        match file_type:
            case 'pdf':
                filepath, filename = convert_to_pdf(obj)
            
            case 'png':
                filepath, filename = convert_to_png(obj)

            case 'jpg':
                filepath, filename = convert_to_jpg(obj)

            case 'svg':
                filepath, filename = convert_to_svg(obj)
            
            case 'jpeg':
                filepath, filename = convert_to_jpeg(obj)

        path = open(filepath, 'rb')
        mime_type, _ = mimetypes.guess_type(filepath)
        response = HttpResponse(path, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response

def learn_more(request):
    return render(request, 'base/coming_soon.html')

def page_not_found(request, exception):
    return render(request, 'base/error404.html', status=404)

templates/qr_generator/dashboard/active_qr.html
{% extends 'qr_generator/dashboard/dashboard.html' %}
{% load static %}

{# Load the style #}
{% block style %}
  <link rel="stylesheet" href="{% static 'dashboard/css/active_qr.css'%}">
{% endblock style %}

{% load humanize %}

{% block specific_content %}

<div class="container">   
  {% if user_items %} 
    <h3>Your Active QR Codes</h3>
    
    
    <div class="active-qr">
      {% for qr in user_items %}
      <figure>
        <img src="{{ qr.qr_code.url }}" alt="">
        <figcaption><b>{{ qr.category }}</b>... <small><i> {{qr.time_created|naturaltime }}</i></small></figcaption>
      </figure>
      {% endfor %}
    </div> 
    

    
  {% else %}
    <img src="{% static 'dashboard/images/active_qr.png'%}" alt="Logo" />                    
    <div class="content">
        <p>You haven't created any QR codes</p>
    </div>
  {% endif %}
  </div>

{% endblock specific_content %}

templates/qr_generator/dashboard/dashboard.html
{% extends 'qr_generator/index.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'dashboard/css/active_qr.css'%}">
{% endblock style %}

 {% block title %}|&nbsp;Active&nbsp;QR{% endblock title %}
   

 {% block content %}
    <section class="dashboard-content">
        <div class="wrapper">
            <div class="sidebar">
            {% block sidebar %}
            <ul>
                <li>
                <a href="#"><i class="uil uil-user-circle"></i>Profile</a>
                </li>
                <li>
                <a href="{% url 'qr_generator:folders'%}"><i class="uil uil-folder-download"></i>My Folders</a>
                </li>
                <li>
                <a href="#"  id="dash-active-page"><i class="uil uil-cloud-check"></i>Active QR Codes</a>
                </li>
                <li >
                <a href="#"><i class="uil uil-clock"></i>History</a>
                </li>
                <li>
                <a href="#"><i class="uil uil-shield"></i>Change Password</a>
                </li>
                <li>
                <a href="#"><i class="uil uil-question-circle"></i>Help</a>
                </li>
                <li>
                <a href="#" class="delete">Delete Account</a>
                </li>
            </ul>
            {% endblock sidebar %}
            </div>


            {% block specific_content %}
            {% endblock specific_content%}
        </div>
    </section>



{% block extra_script %}
{% endblock extra_script %}

{% endblock content %}
{% block top_footer %}{% endblock top_footer %}
{% block middle_footer %}{% endblock middle_footer %}

templates/qr_generator/dashboard/folders.html
{% extends 'qr_generator/dashboard/dashboard.html' %}

{% load static %}

{% block style %}
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
    <link rel="stylesheet" href="{% static 'dashboard/css/folders.css'%}">
{% endblock style %}

 {% block title %}|&nbsp;{{request.user.username|title}}&nbsp;Folders{% endblock title %}
   

 {% block content %}
    <section class="dashboard-content">
        <div class="wrapper">
            <div class="sidebar">
            {% block sidebar %}
            <ul>
                <li>
                <a href="#"><i class="uil uil-user-circle"></i>Profile</a>
                </li>
                <li>
                <a href="{% url 'qr_generator:folders' %}" id="dash-active-page"><i class="uil uil-folder-download"></i>My Folders</a>
                </li>
                <li>
                <a href="{% url 'qr_generator:active_qr' %}" ><i class="uil uil-cloud-check"></i>Active QR Codes</a>
                </li>
                <li >
                <a href="#"><i class="uil uil-clock"></i>History</a>
                </li>
                <li>
                <a href="#"><i class="uil uil-shield"></i>Change Password</a>
                </li>
                <li>
                <a href="#"><i class="uil uil-question-circle"></i>Help</a>
                </li>
                <li>
                <a href="#" class="delete">Delete Account</a>
                </li>
            </ul>
            {% endblock sidebar %}
            </div>


            {% block specific_content %}
                {% if folders %}
                <div class="container">
                    <div class="content">
                        <ul style="float:right;">
                            {% for folder in folders %}
                                <li style="text-decoration:none;"><i class="uil uil-folder-download"></i>{{ folder }}</li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>

                {% else %}
                <div class="container">                    
                    <img src="{% static 'dashboard/images/folders.png'%}" alt="Logo" />                    
                    <div class="content">
                        <p>You have nothing in your folder yet</p>
                    </div>
                </div>
                {% endif %}
            {% endblock specific_content%}
        </div>
    </section>



{% block extra_script %}
{% endblock extra_script %}

{% endblock content %}

templates/qr_generator/dashboard/text_folder.html
<h4>Text Works</h4>
{% for img in %}